server:
  port: 8080

jasypt:
  encryptor:
    password: vedha # Password to jasypt encrypt and decrypt the values

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db
#    Using Jasypt Plugin to encrypt and decrypt the values
#    mvn jasypt:encrypt-value -Djasypt.encryptor.password=vedha -Djasypt.plugin.value=admin
#    mvn jasypt:decrypt-value -Djasypt.encryptor.password=vedha -Djasypt.plugin.value=LJQqKg5E07P0WgEq1/P73R0h/1mp/NKzGrnB5xfjGwL9ltGujAATUbiBi7h3MFnD
#    mvn jasypt:encrypt -Djasypt.encryptor.password=vedha -Djasypt.plugin.path=file:src/main/resources/application-dev.yml
    username: ENC(eEdiJLIe/NHVO/YdEAxgkHmaksWJHCoed2XZd8Mopuv0Uiet/x7135xnNaBbN+23)
    password: ENC(eEdiJLIe/NHVO/YdEAxgkHmaksWJHCoed2XZd8Mopuv0Uiet/x7135xnNaBbN+23)
    name: H2
    hikari:
      pool-name: H2-HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      leak-detection-threshold: 20000
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
          fetch_size: 1000
          batch_versioned_data: true
  flyway:
    enabled: true

logging:
  level:
    com:
      vedha: debug

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
    configprops:
      show-values: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true